# Generated by Django 3.2.4 on 2021-07-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorly_coded_store', '0002_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='selected_items',
        ),
    ]
